#ifndef BB_EXAMPLE_H
#define BB_EXAMPLE_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

#define IN  0
#define OUT 1

#define LOW  0
#define HIGH 1

#define PIN  24 /* P1-18 */
#define POUT 4  /* P1-07 */


extern int GPIOExport(int pin);
extern int GPIOUnexport(int pin);
extern int GPIODirection(int pin, int dir);
extern int GPIORead(int pin);
extern int GPIOWrite(int pin, int value);

#endif /* BB_EXAMPLE_H */



// #ifndef BB_EXAMPLE_H
// #define BB_EXAMPLE_H

// /* Some cross-platform definitions generated by autotools */
// #if HAVE_CONFIG_H
// #  include <config.h>
// #endif /* HAVE_CONFIG_H */

// /*
//  * Example function
//  */
// extern void LibHelloWorld(void);

// #endif /* BB_EXAMPLE_H */
